### ISSUE TITLE
Can you please provide a backport for Python 27 ?

### ISSUE THREAD

**Issue by tarunchhabra26** [anfema/integrate#1]
How can do the same thing in Python 27 ?
`if sys.version_info >= (3, 5):
        import importlib.util
        spec = importlib.util.spec_from_file_location(module_name, filename)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module`

**Comment by dunkelstern** [comment]
Just released Version 1.1.1 which should work on 2.7
